-- Canonical coverage for non-municipality / non-region organizations.
--
-- One row per organization -> municipality coverage mapping.
-- Region-wide organizations should have many rows, one for each municipality covered.

CREATE TABLE IF NOT EXISTS public.org_municipality_coverage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_key text NOT NULL,
  region_key text,
  municipality_key text NOT NULL,
  authority_scope text,
  coverage_method text,
  source_org_type text,
  source_org_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_municipality_coverage_org_muni
  ON public.org_municipality_coverage (organization_key, municipality_key);

CREATE INDEX IF NOT EXISTS idx_org_municipality_coverage_org_key
  ON public.org_municipality_coverage (organization_key);

CREATE INDEX IF NOT EXISTS idx_org_municipality_coverage_region_key
  ON public.org_municipality_coverage (region_key);

CREATE INDEX IF NOT EXISTS idx_org_municipality_coverage_municipality_key
  ON public.org_municipality_coverage (municipality_key);

GRANT SELECT ON public.org_municipality_coverage TO anon, authenticated, service_role;
